### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by HGeo** [jacogr/atom-git-control#245]
1. Install Git-control package
2. Reload Atom
3. Invoke git-control

**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Windows 10 15063.608
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At C:\Users\rhinov14e.RHINOV\.atom\packages\git-control\lib\git-control-view.coffee:76

TypeError: Cannot read property 'split' of undefined
    at GitControlView.module.exports.GitControlView.initialize (/packages/git-control/lib/git-control-view.coffee:76:50)
    at /packages/gulp-control/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/git-control/lib/git-control-view.coffee:36:7)
    at Object.toggleView (/packages/git-control/lib/git-control.coffee:31:18)
    at /packages/git-control/lib/git-control.coffee:18:57)
    at CommandRegistry.handleCommandEvent (C:/atom/app-1.22.0-beta0/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:/atom/app-1.22.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:/atom/app-1.22.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:/atom/app-1.22.0-beta0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:/atom/app-1.22.0-beta0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:36.6.0 core:delete (input.hidden-input)
     -1:28.2.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.6.0 docblockr:parse-enter (input.hidden-input)
     -1:21.6.0 editor:newline (input.hidden-input)
     -1:18 core:move-right (input.hidden-input)
     -1:15.8.0 core:paste (input.hidden-input)
     -1:13.8.0 core:save (input.hidden-input)
     -0:49.8.0 git-control:toggle (input.hidden-input)
 11x -0:26.4.0 editor:move-line-up (input.hidden-input)
     -0:24.1.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:23.9.0 docblockr:parse-tab (input.hidden-input)
     -0:23.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:23.9.0 snippets:expand (input.hidden-input)
     -0:23.9.0 editor:indent (input.hidden-input)
     -0:22.8.0 core:save (input.hidden-input)
  2x -0:15.5.0 git-control:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.4.0 
change-case 0.6.5 
docblockr 0.11.0 
file-icons 2.1.12 
git-control 0.9.0 
gulp-control 0.5.0 
ide-flowtype 0.17.4 
ide-typescript 0.6.1 
language-markdown 0.25.1 
split-diff 1.5.1 
```

**Comment by anthfran** [comment]
Seeing this too...
Atom: 1.21.1
OS: OSX 10.13
Thrown From: git-control package 0.9.0

**Comment by solartune** [comment]
Today I have the same problem... Yesterday everything was fine
Atom: 1.21.1
OS: macOS 10.12.6

**Comment by jayspirits** [comment]
ive encountered this issue today and checked the code and found out that theres a string value from an object that needs to be split that is no longer available. i fixed it on my end and already submitted a PR regarding this issue.

**Comment by dlwlsgjs** [comment]
I solved this by clearing this git-control\lib\git-control-view.coffee:76 line

**Comment by aeisma** [comment]
As a workaround you can replace .path with .getPath() in the git-control/lib/git-control-view.coffee:76 and the git-control/lib/dialogs/project-dialog.coffee:33 lines.

**Comment by krl91** [comment]
Hello, this issue is still present in the very last version of atom and the git-control plugin installled with the package manager include in atom.
Could you correct this issue? in other case git-control is useless for me (I can do absolutely nothing !)
